import { ProductCardItem } from '../commons/Types';

export const MOCK_PRODUCT_LIST: ProductCardItem[] = [
  {
    productId: 'product_10001',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_pink'),
    promotion: ['任选2件7.5折,任选3件7折'],
    label: [
      {
        preset: 0,
        data: '上新折扣',
      },
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_10002',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_white'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_10003',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_stripe'),
    promotion: ['8.5折'],
    label: [],
  },
  {
    productId: 'product_10004',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_green'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_10001',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_pink'),
    promotion: ['任选2件7.5折,任选3件7折'],
    label: [
      {
        preset: 0,
        data: '上新折扣',
      },
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_10002',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_white'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_10003',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_stripe'),
    promotion: ['8.5折'],
    label: [],
  },
  {
    productId: 'product_10004',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_green'),
    promotion: [],
    label: [],
  },
];
