export enum RouterMap {
  SETTING = 'SettingPage',
  AGREEMENT = 'AgreementPage',
  USER_LOGIN = 'HuaweiQuickLoginPage',
  USER_OTHER_LOGIN = 'OtherLoginPage',
  USER_PROFILE_EDIT = 'EditProfilePage',

  PRODUCT_SEARCH = 'ProductSearchPage',
  PRODUCT_SEARCH_RESULTS = 'ProductSearchResultsPage',
  PRODUCT_INFO = 'ProductInfoPage',
  PRODUCT_INFO_NEW = 'ProductInfoPageNew',
  PRODUCT_CATEGORY = 'CategoryPage',
  PRODUCT_CART = 'CartPage',

  ORDER_SUBMIT = 'OrderSubmitPage',
  ORDER_SEARCH = 'OrderSearchPage',
  ORDER_LIST = 'OrderListPage',
  ORDER_INFO = 'OrderInfoPage',
}